/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Potrace
 #	author : miyako
 #	2016/09/23
 #
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Potrace.h"

#include "backend_svg.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
            // --- Potrace
            
            case 1 :
            Potrace(params);
            break;
        
        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Potrace(PA_PluginParameters params) {
    
}
